### PR TITLE
支持加载ini文件为程序添加翻译，这样那样的修复&效能改进

### PR DESCRIPTION
**Pull request by lrisora**
#### New language translations will be in the following format for the INI files:
- The file encoding is UTF-8 with BOM.
- Line endings are CRLF.
- File names are based on the English name of the language, using underscores instead of spaces. Once released, file names will be difficult to change, so language variants need to be considered.
- Lines starting with '#' or ';' are considered comments.
- For ease of maintenance, please do not change the order of lines or the position of empty lines.
- String values should be enclosed in double quotes. Some value strings contain special characters like []<>, which should be preserved as is.
- Use `\r\n` to represent line breaks.
- INI escape characters are as follows: `\r\n` -> line break, `\t` -> tab, `\;` -> `;`, `\#` -> `#`, `\\` -> `\`.
- For the MFC framework, '&' is a special character. In some cases, double escaping may be necessary. If necessary, please check the actual display.
- In menu text, '&' indicates that the next character is a mnemonic key. If the translated language uses mnemonic keys, appropriate mnemonic keys can be assigned to menu items. However, please do not use mnemonic keys in locations other than menus for maintenance purposes.
- The MFC framework is old, and the program UI can only adapt to translated text lengths to a limited extent. If there are interface elements that cannot accommodate translated text and it is difficult to shorten the translation, please @lrisora to adjust the UI layout.
- English/Chinese translations may have errors in previous migrations. If there are errors/inappropriate translations, please point them out.

#### The [general] section is for translation configuration, including the following key-value pairs:
- BCP_47: The language's BCP-47 code.
- DISPLAY_NAME: The language name displayed in the program settings.
- TRANSLATOR: The translator(s), using the format "aa","bb","cc" if there are multiple translators.
- DEFAULT_FONT: The default font for the language. Currently, due to program issues, if this font is not provided by default on all Windows languages (e.g., Segoe UI/Arial), please comment out this line after filling it in.

**媒体库更新代码重写，暂时缺少测试** （只有我试过，多半没问题，但无法保证）
为避免媒体库数据丢失请备份 `song_data.dat` 
特别的，patch01的提交是半成品状态，仅限测试使用，媒体库会出问题

其他变更等我整理一下

### CODE REVIEW

**Comment by lrisora** [comment]
我有那三个大型提交的内部历史 ~混乱的一锅粥~ ，没有起有意义的名字，所以是压缩之后提交的
如果需要可以发出来

不兼容更新：
媒体库窗口大小保存位置改变
自定义UI加载资源字符串更改，之前的资源ID现在改为翻译ini中[text]段的键字符串
不再支持内嵌cue（之前的也很有问题）
设置的“媒体库强制重新加载按钮”强度更改，现在与“重新载入播放列表”一致，范围为媒体库目录
桌面歌词渐变色有些变化，可能需要修改默认值

关于程序会使用哪个字体现在有那么一点问题，
<language>.ini中可以设置字体，如果没有设置则使用当前系统的默认字体
这是不合理的但是我没想到更好的解决方法

主要改善程序启动速度（3s->2s）与编译速度（5min->1min）

好像没有合并冲突，github应该是搞错了，在本地可以直接合并

**Comment by zhongyang219** [comment]
感谢改进，这是个相当大的工作量

**Comment by lrisora** [comment]
有一个特殊优势，窗口设计器布局的时候能看到英文文本长度，比较方便决定预留多少空间

**Comment by lrisora** [comment]
另一个原因是ini中的键优先考虑的是翻译时候方便，直接指出字符串的意义与用途，相当于注释
写代码就累一点，为了翻译方便我认为可以接受
字符串有各种特殊情况，还有复用的问题，如果折腾通用方法只是处理特殊情况写代码花的时间也差不多
那些平常的（不特殊的）控件几乎不花时间，阵列编辑就好了虽然代码长一点，迁移时时间都耗在那些特殊情况上了

要是放弃翻译方便的优势的话直接用控件的ID字符串做键也可以用窗口ID字符串做段名，就像菜单那样
仍然会多出一堆特殊情况的字符串需要沿用旧办法
也可能需要为翻译字符串维护一个文档，解释各个位置的意义

菜单因为助记键天生就有同一个命令ID的字符串出现在不同菜单中就会不同的情况所以不算冗余

**Pull request merged**
